### ISSUE TITLE
Nothing could be deleted

### ISSUE THREAD

**Issue by panb** [rgoraya/wc_master#9] opened 2011-11-02 21:47 UTC
It shows the term is deleted, then it logs me out. The term is still there after I log back in.

**Comment by duyetln** [comment] 2011-11-02 22:07
That is the expected behavior. Since we don't release the system to the public yet, we still need to use the lock. By default, the lock will not allow any deletions. Please also tell other members about this.

**Comment by dLobatog** [comment] 2011-11-05 01:23
Close the issue then Nguyen

**Closed as completed** 2011-11-05 06:14 UTC
